spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Zeng19980715**

mybatis:
  type-aliases-package: com.zeng.pojo         #实体类包别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件
  configuration:                              #驼峰映射
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.zeng: debug
  file:
    name: log/bolg-dev.log


server:
  port: 8080
